"""
Freeze the Animora bundled backend into a standalone Windows folder.

Produces:  build/backend-dist/animora-backend/animora-backend.exe  (+ deps)
           build/backend-dist/animora-backend/animora_backend.env  (Bedrock creds)
           build/backend-dist/bundle_config.json                   (addon marker)

The Inno installer (installer/windows/inno/Animora.iss) ships:
  • build/backend-dist/animora-backend/*  ->  {app}/engine/
  • build/backend-dist/bundle_config.json →  the addon dir

Why the copy-to-underscore dance:
  The source dir is `ai-backend/` (hyphen) which Python can't import. We
  copy it to build/backend-build/ai_backend/ (underscore) and write a
  run_backend.py entry that does `from ai_backend.bundled_server import
  main`. PyInstaller then follows REAL imports and discovers the whole
  dependency graph automatically — far more robust than hand-maintaining
  a hidden-imports list. The .spec only layers on the data-file collectors
  PyInstaller's static analysis can't see (botocore service JSON, etc.).

Run (from repo root, in the venv that can already run dev_server.py):
    python scripts/freeze_backend.py
Requires: pip install pyinstaller
"""

from __future__ import annotations

import logging
import os
import shutil
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger("freeze_backend")

REPO_ROOT = Path(__file__).resolve().parent.parent
AI_BACKEND = REPO_ROOT / "ai-backend"
BUILD_BUILD = REPO_ROOT / "build" / "backend-build"
BUILD_WORK = REPO_ROOT / "build" / "backend-work"
DIST = REPO_ROOT / "build" / "backend-dist"
SPEC = AI_BACKEND / "animora_backend.spec"

# Source items NOT copied into the importable package. Keeps the bundle
# slim and keeps dev-only / secret files out of the frozen artifact.
_COPY_IGNORE = shutil.ignore_patterns(
    "__pycache__", "*.pyc", "*.pyo",
    ".env", ".env.*",
    "dev_server.py",          # dev-only; bundled_server.py is the ship entry
    "animora_backend.spec",
    "tests",                  # smoke tests not needed at runtime
    "recordings",             # any local capture output
    "*.log",
)

_RUN_ENTRY = """\
# Auto-generated by scripts/freeze_backend.py — do not edit.
from ai_backend.bundled_server import main

if __name__ == "__main__":
    main()
"""

_BUNDLE_CONFIG = """\
{
  "mode": "recording",
  "backend_exe": "engine/animora-backend.exe",
  "health_url": "http://localhost:8000/health",
  "backend_ws": "ws://localhost:8000/ws",
  "auto_signin": true,
  "auto_record": true,
  "startup_timeout_sec": 40
}
"""


def _clean() -> None:
    for d in (BUILD_BUILD, BUILD_WORK, DIST):
        if d.exists():
            log.info("removing %s", d)
            shutil.rmtree(d)
    BUILD_BUILD.mkdir(parents=True, exist_ok=True)


def _copy_package() -> None:
    dst = BUILD_BUILD / "ai_backend"
    log.info("copying %s  →  %s", AI_BACKEND, dst)
    shutil.copytree(AI_BACKEND, dst, ignore=_COPY_IGNORE)
    # Entry point that PyInstaller analyses.
    (BUILD_BUILD / "run_backend.py").write_text(_RUN_ENTRY, encoding="utf-8")
    log.info("wrote entry %s", BUILD_BUILD / "run_backend.py")


def _run_pyinstaller() -> int:
    try:
        import PyInstaller.__main__ as pyi
    except ImportError:
        log.error("PyInstaller not installed. Run: pip install pyinstaller")
        return 1
    # ANIMORA_ENV=dev so any import of ai_backend.config during PyInstaller's
    # analysis passes _enforce_secrets_safety (the repo ships a dev-sentinel
    # JWT secret; without this the analysis import would raise).
    os.environ.setdefault("ANIMORA_ENV", "dev")
    os.environ.setdefault("ANIMORA_LLM_PROVIDER", "bedrock")
    args = [
        str(SPEC),
        "--distpath", str(DIST),
        "--workpath", str(BUILD_WORK),
        "--noconfirm",
        "--clean",
    ]
    log.info("running PyInstaller: %s", " ".join(args))
    pyi.run(args)
    return 0


def _recording_env_file_contents() -> str:
    """The animora_backend.env text shipped next to the frozen exe.

    SECURITY (Bug 6): this file is inside the installer and is trivially
    extractable, so it MUST NOT contain the Bedrock key — that was the only
    client-embedded credential left in the whole product. It carries the
    NON-SECRET region only. The recording operator supplies the key at
    runtime via the AWS_BEARER_TOKEN_BEDROCK environment variable on their
    own machine; bundled_server._load_bundled_env uses setdefault, so a
    process env var always takes precedence over this file. Pure function so
    it can be unit-tested (asserting no key ever leaks in)."""
    return "\n".join([
        "# Animora recording-build backend config (NON-SECRET).",
        "# Shipped inside the installer next to animora-backend.exe.",
        "#",
        "# The Bedrock key is DELIBERATELY NOT here (it would be extractable",
        "# from the bundle). Set it in your shell before launching Animora:",
        "#   Windows:      set AWS_BEARER_TOKEN_BEDROCK=ABSK...",
        "#   macOS/Linux:  export AWS_BEARER_TOKEN_BEDROCK=ABSK...",
        "# bundled_server prefers the process env var over this file.",
        "BEDROCK_AWS_REGION=us-east-1",
        "",
    ])


def _write_bundle_files() -> int:
    app_dir = DIST / "animora-backend"
    if not app_dir.is_dir():
        log.error("PyInstaller did not produce %s — build failed", app_dir)
        return 1

    (app_dir / "animora_backend.env").write_text(
        _recording_env_file_contents(), encoding="utf-8",
    )
    log.info(
        "wrote KEY-FREE animora_backend.env (region only) — the operator "
        "supplies AWS_BEARER_TOKEN_BEDROCK via the environment at runtime",
    )

    (DIST / "bundle_config.json").write_text(_BUNDLE_CONFIG, encoding="utf-8")
    log.info("wrote %s", DIST / "bundle_config.json")

    exe = app_dir / "animora-backend.exe"
    if not exe.is_file():
        log.error("MISSING %s — bundle is broken", exe)
        return 1
    log.info("OK: frozen backend at %s", exe)
    return 0


def main() -> int:
    if not AI_BACKEND.is_dir():
        log.error("ai-backend/ not found at %s", AI_BACKEND)
        return 1
    if not SPEC.is_file():
        log.error("spec not found at %s", SPEC)
        return 1
    _clean()
    _copy_package()
    rc = _run_pyinstaller()
    if rc != 0:
        return rc
    return _write_bundle_files()


if __name__ == "__main__":
    sys.exit(main())
